GET http://localhost:8899
###

GET http://localhost:8899/api/post
###

POST http://localhost:8899/api/auth/login
Content-Type: application/json

{
    "identuty": "andy@cc21.web",
    "password": "1234"
}

###

POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
 # "identity" : "1234567890",
  "identity" : "someone1@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "1234567",
 "confirmPassword" : "1234567"
}

###
