GET http://localhost:8899
###

GET http://localhost:8899/api/post
###

POST http://localhost:8899/api/auth/login
Content-Type: application/json

{
    "identuty": "andy@cc21.web",
    "password": "1234"
}

###

POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
 # "identity" : "1234567890",
  "identity" : "someone3@ggg.mail",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}

###

# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "someone2@ggg.mail",
 "password" : "123456"
}
###

# Get me

GET http://localhost:8899/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsImlhdCI6MTc2MTc5NzA3MywiZXhwIjoxNzYzMDkzMDczfQ.otGAiSFBMIdyocNcM7Gr0urJWCbdKibTcO2uaCo6sQs
###